name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: checkboxes
    id: otherIssues
    attributes:
      label: Please search to see if an issue already exists for the bug you encountered, and that it hasn't been fixed in a recent build/commit.
      options:
        - label: I have searched the existing issues
          required: true


  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: dropdown
    id: webui
    attributes:
    multiple: true
      label: Which WebUI
      description: What WebUI do you use?
      options:
        - AUTOMATIC1111 (Default)
        - Vladmandic (not tested)
    validations:
      required: true

  - type: dropdown
    id: webui-version
    attributes:
    multiple: true
      label: WebUI version
      description: Which WebUI version do you use?
      options:
        - 1.4.*
        - 1.3.*
        - 1.2.*
        - 1.1.*
    validations:
      required: true

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge

  - type: dropdown
    id: py-version
    attributes:
      label: What Python version are you running on?
      multiple: false
      options:
        - Python 3.10.x
        - Python 3.11.x (above, no supported yet)
        - Python 3.9.x (below, no recommended)

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce the problem
      description: Please provide us with precise step by step information on how to reproduce the bug
      value: |
        1. Go to .... 
        2. Press ....
        3. ...
    validations:
      required: true

  - type: textarea
    id: extensions
    attributes:
      label: List of extensions
      description: Are you using any extensions other than built-ins and this one? If yes, provide a list, you can copy it at "Extensions" tab. Write "No" otherwise.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please provide **full** cmd/terminal logs from the moment you started UI to the end of it, after your bug happened. If it's very long, provide a link to pastebin or similar service. This will be automatically formatted into code, so no need for backticks.
      render: shell
